server:
  forward-headers-strategy: framework
  port: ${MYBURGUER_SERVER_PORT:8080}
  shutdown: graceful
  servlet:
    context-path: /api/v1
spring:
  application.name: myburguercontrol
  config:
    import: optional:file:.env[.properties]
  datasource:
    schema: myburguer
    url: jdbc:${DATABASE_URL}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
    driverClassName: org.postgresql.Driver
    maxActive: 10
    maxIdle: 5
    minIdle: 2
    initialSize: 5
    removeAbandoned: true
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
    properties:
      hibernate:
        default_schema: ${spring.datasource.schema}
        jdbc.batch_size: 20
        cache:
          use_query_cache: false
          use_second_level_cache: false
          use_structured_entries: false
          use_minimal_puts: false
  liquibase:
    change-log: classpath:/db/changelog/master.xml
    enabled: true
    default-schema: ${spring.datasource.schema}

third-party:
  payment-integration:
    url: http://localhost/mercadopago/pagamento
    connectionTimeout: 5000
    readTimeout: 5000

springdoc:
  version: '@springdoc.version@'
  swagger-ui:
    use-root-path: true
  path: /api/v1/swagger-ui/index.html

logging:
  level:
    org:
      springframework:
        web: ${LOG_LEVEL:DEBUG}
    io:
      github:
        soat7:
          myburguercontrol: ${LOG_LEVEL:DEBUG}

jwt:
  key: ${JWT_KEY}
  access-token-expiration: 3600000
  refresh-token-expiration: 86400000
